### PR TITLE
add deploy docker images workflow

### PR DESCRIPTION
**Pull request by qsliu2017**
Add a workflow to build and deploy docker images

### CODE REVIEW

**Comment by kagaya85** [comment]
could this workflow be set to build and push image when tag a new version?

**Comment by qsliu2017** [comment]
> could this workflow be set to build and push image when tag a new version?

Yes, the workflow can be set to run when pushing commits with a tag. see https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags

Should we set a tag like `release` or something?

**Comment by kagaya85** [comment]
yeah, we'd better trigger this workflow when tag a new version

**Comment by qsliu2017** [comment]
> yeah, we'd better trigger this workflow when tag a new version

I modify the workflow. Now this workflow is triggered by tag `v[0-9]+.[0-9]+.[0-9]+` like `v0.2.0`, and the images' tag can be extracted from it. see action in my repo https://github.com/qsliu2017/train-ticket/actions/runs/1115806761

**Comment by kagaya85** [comment]
LGTM

**Review by kagaya85 — APPROVED** [review]

**Pull request merged**
